apiVersion: grafana.sphc.io/v1alpha1
kind: Grafana
metadata:
  name: simple
  namespace: grafana-operator
spec:
  resources:
    requests:
      memory: 256M
      cpu: 100m
    limits:
      memory: 500M
      cpu: 500m
